apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-mysql
spec:
  selector:
    matchLabels:
      app: directory-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: directory-mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
